### ISSUE TITLE
what the difference of  implementing position sensitive ROI Pooling layer between this repo and the repo of py-R-FCN-multiGPU?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [bharatsingh430/soft-nms#11]
Hi @bharatsingh430,

what the difference of  implementing position sensitive ROI Pooling layer between this repo and the repo of py-R-FCN-multiGPU? Is it that you have fixed the alignment problem in this repo?

Thanks.

**Comment by bharatsingh430** [comment]
I implemented psroipooling like in mask-rcnn and it obtains 1% better results on coco

**Comment by zimenglan-sysu-512** [comment]
hi @bharatsingh430,

thanks.
btw, Is there any difference in code between `soft-nms` and `py-R-FCN-multiGPU` repos?

**Comment by bharatsingh430** [comment]
soft-nms includes soft-nms implementation and bilinear interpolation in psroipooling. rest is the same.
