### ISSUE TITLE
Does this repository include deformable convolution?

### ISSUE THREAD

**Issue by SunGaofeng** [bharatsingh430/soft-nms#15]
As stated in the ICCV paper of soft-NMS,  deformable convolution of RFCN was implemented. 
Does this repository also include deformable RFCN?

**Comment by bharatsingh430** [comment]
this repo contains it 

https://github.com/bharatsingh430/Deformable-ConvNets

**Comment by SunGaofeng** [comment]
Thanks. I just read that repo, and found that it was implemented in mxnet.
This repo is implemented in caffe. So do you have a caffe version deformable rfcn?

**Comment by bharatsingh430** [comment]
The deformable psroilayer can be found here, https://github.com/soeaver/py-RFCN-priv/blob/master/caffe-priv/src/caffe/layers/deformable_psroi_pooling_layer.cu but I am not sure if deformable convolution is implemented in caffe. I see something here, https://github.com/unsky/Deformable-ConvNets/blob/master/src/caffe/layers/deformable_conv_layer.cu but I have not tested it.

**Comment by SunGaofeng** [comment]
Thanks to your reply. This issue is a little diverged of this soft-nms repo,  thanks to your patient to answering this question.
I'll read the caffe related code and test it.
