### ISSUE TITLE
how to measure location accuracy？？

### ISSUE THREAD

**Issue by foralliance** [bharatsingh430/soft-nms#16]
In this paper, the concept of  “precision localization / localization Performance” are mentioned in many places, Is there a specific standard to measure it??
In my option, The paper is measured by setting different overlap thresholds, and then testing the corresponding AP values. is that right??

**Comment by wuzzh** [comment]
Yes, it's right.





在 2017-12-22 14:21:43，"foralliance" <notifications@github.com> 写道：


In this paper, the concept of “precision localization / localization Performance” are mentioned in many places, Is there a specific standard to measure it??
In my option, The paper is measured by setting different overlap thresholds, and then testing the corresponding AP values. is that right??
