### ISSUE TITLE
Why Soft-NMS has the same computational complexity traditional NMS ?

### ISSUE THREAD

**Issue by Dawn-LX** [bharatsingh430/soft-nms#31]
![image](https://user-images.githubusercontent.com/48169011/71540748-ba3c6500-2989-11ea-99bd-e45805f1dcd7.png)
我觉得softNMS复杂度应该要比传统的hard-NMS高一点？
因为在hard-NMS中，集合B是逐渐变小的，也就是说内层循环的次数并非每次都是N，或者说按照作者的说法，将hard-NMS视为用了a discontinuous binary weighting function，对s_i赋值为0，那么在for 循环中应该加一个s_i ！=0的判断。如果s_i ==0 就不把相应的b_i和b_m 进行计算IoU的操作。

softNMS 的复杂度是O( N(N-1)/2 )
而对于hard-NMS，如果考虑每个object都有2个重叠得很近的框的话，复杂度是O(N^2 / 4), 是softNMS的一半，如果每个object的重叠框更多的话，复杂度就比softNMS更低

————————————————————————
soft NMS has the computational complexity of O(N(N-1)/2) , while as for hard-NMS, if each object has at least 2 overlap bboxes, then it has the computational complexity of O(N^2/4), which is half of soft-NMS. And if each object has more overlapped bboxes, even low complexity....
Am I Right ?????????

**Comment by bharatsingh430** [comment]
Complexity is measured in order of magnitude, like O(n^2) or O(n log n). Constants don’t affect it.

**Comment by Dawn-LX** [comment]
> Complexity is measured in order of magnitude, like O(n^2) or O(n log n). Constants don’t affect it.

Thank you, I thought that constant doesn't affect complexity means O(n^2) has the same complexity as O((n+c)^2).  That's it, the magnitude is also counts as  constant. Thank you for your explanation
