### ISSUE TITLE
Error with info "argmax of an empty sequence" while training on COCO dataset

### ISSUE THREAD

**Issue by crazylyf** [bharatsingh430/soft-nms#4]
Hi all,

When I tried to train on COCO dataset, the program exit with information: `ValueError: attempt to get argmax of an empty sequence`. Has anyone encountered such an problem?

**Comment by baiyancheng20** [comment]
`def train_net_multi_gpu(solver_prototxt, roidb, output_dir, pretrained_model, max_iter, gpus):
    """Train a Fast R-CNN network."""
    **roidb = filter_roidb(roidb)**
    uid = caffe.NCCL.new_uid()`

**Comment by baiyancheng20** [comment]
`def train_net_multi_gpu(solver_prototxt, roidb, output_dir, pretrained_model, max_iter, gpus):`
    `"""Train a Fast R-CNN network."""`
    **roidb = filter_roidb(roidb)**
    `uid = caffe.NCCL.new_uid()`

Add the bold line to filter some images without any annotations.

**Comment by crazylyf** [comment]
thx @baiyancheng20
