### ISSUE TITLE
problem about the precision-recall curve

### ISSUE THREAD

**Issue by 1292765944** [bharatsingh430/soft-nms#7]
I notice that you set a lower confidence threshold for detector than default in Faster R-CNN. Is this help for calculating accurate AP? Or lower threshold means better AP? https://github.com/bharatsingh430/soft-nms/blob/master/lib/fast_rcnn/test.py#L232

Best!

**Comment by bharatsingh430** [comment]
0.001 will also give the same result. In r-fcn it is set to -inf. Higher threshold makes soft-nms a bit faster.
